### ISSUE TITLE
Wrong format not accepted by freeagent

### ISSUE THREAD

**Issue by ivanperez-keera** [pbowyer/transferwise-to-freeagent#2]
After running this script, my file is just several lines like:

```
,,undefined (Fee undefined)
```

and nothing else.

**Comment by pbowyer** [comment]
Sorry to hear you're having problems. 

Can you tell me which browser you used when you went to https://pbowyer.github.io/transferwise-to-freeagent/?

To investigate further I'll need a copy of your Transferwise CSV, as I'm using this tool each month with my export and not having problems :)

**Comment by pbowyer** [comment]
Closing this ticket as I've received no feedback.
