### ISSUE TITLE
Generated file doesn't have transactions

### ISSUE THREAD

**Issue by joecw** [pbowyer/transferwise-to-freeagent#4]
Thanks for creating this useful tool!

However, I cannot get it to work. 

I uploaded my CSV file that I downloaded from Transferwise.

The file I downloaded from Github only contained this for each row:

  |   | undefined (Fee   undefined)-- | -- | --

I'm using Chrome browser. 

Thanks,
Joe

**Comment by pbowyer** [comment]
Sorry to hear you're having problems.

To investigate further I'll need a copy of your Transferwise CSV, as I'm using this tool each month with my export and not having problems. The output you're getting suggests the file format can't be parsed.

**Comment by joecw** [comment]
Hi Peter,

Thanks for getting back to me! 
Can I send it to you privately please?

Thanks.
