### ISSUE TITLE
Can't download file

### ISSUE THREAD

**Issue by dannyparsons** [pbowyer/transferwise-to-freeagent#5]
I think I must be missing something simple but I can't see how to download the converted file after uploading. Here is a screenshot of what I see. What do I need to do to get the converted file? I was looking for a convert/download button to appear?

![image](https://user-images.githubusercontent.com/11214914/71313806-c5493f80-2435-11ea-825f-b6cc8453f619.png)

**Comment by logiclabs** [comment]
I had the same on a Windows computer.  There is a check on the file type, which doesn't appear to work in Windows.  I've now submitted a pull request #6 to fix this.

**Comment by pbowyer** [comment]
Thank you for contributing, I've merged this pull request into the code.
